# Generated by Django 3.0.5 on 2020-04-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersearches',
            name='search_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
